### GET ALL ROLES
GET http://localhost:8002/api/permissions
### ADD NEW ROLE
POST http://localhost:8002/api/permissions
Content-Type: application/json

{
    "name":"leader",
    "guard_name":"web",
    "permission":1
}

### for sending permissions
GET http://localhost:8002/permi
