### GET ALL USERS
GET http://localhost:8000/api/users
### ADD NEW USER
POST http://localhost:8000/api/users
Content-Type: application/json

{
    "name":"Adebayo",
    "email":"Adebayo@Ishola.com",
    "password":"123456789"
}
